name: Deploy to Firebase Hosting on Merge

'on':
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Firebase Authentication
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VISITING_CARD_6E1FC }}' > firebaseServiceAccount.json
          firebase auth:login --token "$(cat firebaseServiceAccount.json)"

      - name: No Build Needed
        run: echo "No build needed"

      - name: Deploy to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VISITING_CARD_6E1FC }}"
